
# A string used as a project reference
project_id = "tnwgtlyuabpmxsqiyjof"
[api]
enabled = true
[db]
enabled = true
[realtime]
enabled = true
[storage]
enabled = true
[auth]
enabled = true
# Configure the Edge Functions
[functions]
[functions.redeem-voucher]
verify_jwt = true
